### ISSUE TITLE
[문제] 백준 / 브론즈2 / 1100 - 하얀 칸

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#106]
## 링크

https://www.acmicpc.net/problem/1100
## 비고

시험 보느라 고생했습니다. 쉬운 문제로 힐링합시다... 

D-173

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96391013-270f3d00-11f2-11eb-803a-313710fb1366.png)

힐링.. 해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/96545830-1c34d500-12e4-11eb-8dc3-fb638db0703d.png)

해결했습니다! 힘냅시다!
