### ISSUE TITLE
 [2020.10.22] 백준 / 골드 3 / 2146 - 다리 만들기

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#116]
## 링크

<https://www.acmicpc.net/problem/2146>

## 비고

다리를 만들어보아요 오늘도 화이팅!^O^

D - 171

**Comment by OctopusSwellfish** [comment]
매번 좋은 문제 감사합니다!

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96829054-c2fbab80-1473-11eb-832c-326991896d6d.png)

해결하였습니다. 근데 좀 찜찜하게 풀었습니다... 문제 조금만 수정되면 틀릴 것 같습니다. ㅠㅠ
