### ISSUE TITLE
[2020.10.23] 백준 / 골드 4 / 6087 - 레이저 통신

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#120]
## 링크

<https://www.acmicpc.net/problem/6087>

## 비고

레이저로 통신해보아요 오늘도 화이팅! ^O^

D - 170

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96977906-b0a76d80-1558-11eb-9778-45c354a6ae73.png)

해결하였습니다.. 쉬운 문제인데 집중력이 너무 낮아서 못풀고 정답 풀이 참조하였습니다 ㅠㅠ

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/97103467-03fff400-16f0-11eb-83df-6decbee77097.png)
해결했습니다. visited부분 처리에 애먹어서 한 번 틀렸는데 배울 거리가 생겼던 것 같습니다
