### ISSUE TITLE
[문제] 백준 / 실버2 / 16987 - 계란으로 계란치기

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#121]
## 링크

https://www.acmicpc.net/problem/16987
## 비고

한 번 풀어보면 좋을 것 같아 추가합니다.

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/97271924-8fa28d80-1874-11eb-9556-7baee43d2b9e.png)

해결하였습니다. 재귀로 풀어야했는데 초기 접근방법조차 알지 못하여 정답코드 참고하였습니다.. ㅠㅠ..
