### ISSUE TITLE
[2020.10.27] 백준 / 골드 1 / 1194 - 달이 차오른다, 가자.

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#129]
## 링크

<https://www.acmicpc.net/problem/1194>

## 비고

가슴이 웅장해진다.. 달이차오른다.. 가자..

D - 166

**Comment by OctopusSwellfish** [comment]
zzzㅋㅋㅋㅋㅋ송은주안현진 백준수준 ㄹㅇ 실화냐? 가슴이웅장해진다...진짜옛날엔브론즈4도못풀었던 그안현진이맞나?
