### ISSUE TITLE
[2020.11.02] 백준 / 실버 1 / 1697 - 숨바꼭질

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#145]
## 링크

<https://www.acmicpc.net/problem/1697>

## 비고

플어야 할 문제가 많으니 조금 쉬운 문제로 가겠습니다. 오늘도 화이팅!^O^

D - 160

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/97831406-4a1e0e80-1d13-11eb-85e9-eff11cb75ea3.png)
해결 했습니다~~ ㅎㅎ

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/97832601-94ed5580-1d16-11eb-8e92-d3ce6919335c.png)

해결하였습니다~
