### ISSUE TITLE
[2020.11.27] 백준 / 골드 5 / 14502 - 연구소

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#201]
## 링크

<https://www.acmicpc.net/problem/14502>

## 비고

풀었던 문제 복습해봅시다! 오늘도 화이팅~ ^o^

D - 135

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/100493709-fcaf8880-317c-11eb-88d7-1ee352869d51.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/100542025-09ba9d80-328b-11eb-8aac-3c06eb78d71c.png)
해결했습니다!!!
