### ISSUE TITLE
[2020.11.29] 백준 / 실버 3 / 14889 - 스타트와 링크

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#204]
## 링크

<https://www.acmicpc.net/problem/14889>

## 비고

오늘도 화이팅~ ^O^

D - 133

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/100521744-bf80e000-31e8-11eb-879a-68097bbef4c1.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/100546139-f87d8b00-32a2-11eb-9662-f5b33f8ca060.png)
해결했습니다~
