### ISSUE TITLE
[문제] 백준 / 실버1 / 20055 - 컨베이어 벨트 위의 로봇

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#206]
## 링크

https://www.acmicpc.net/problem/20055
## 비고

삼성 기출입니다~~

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/100878554-b2683780-34ed-11eb-8e84-feff00aec637.png)
풀었습니다! 실제 시험장에서 풀었던거와 같은 방식으로 풀었는데 1초 104나오네요... 꽤나 비효율적인 코드였나봅니다 ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/100889208-3aecd500-34fa-11eb-8279-267b5e70eaa1.png)

해결하였습니다.
