### ISSUE TITLE
[2020.12.27] 백준 / 플레 5 / 2842 - 집배원 한상덕

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#252]
## 링크

<https://www.acmicpc.net/problem/2842>

## 비고

오랜만에 매운 맛을 해봅시다! 오늘도 화이팅~ ^O^

D - 105

**Comment by OctopusSwellfish** [comment]
플레 잔인하네요 ;;골드 5도 피똥쌉니다 ㅜㅜ

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/103280748-7bb20e00-4a14-11eb-9406-734cc7732c1a.png)

해결하였습니다. 어려우면서도 신기한 유형의 문제였습니다.
