### ISSUE TITLE
[문제] 백준 / 실버4 / 1940 - 주몽

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#261]
## 링크

https://www.acmicpc.net/problem/1940
## 비고

문제는 엄청 쉽지만.. 어떻게 하면 더 빠르게 풀 수 있을까에 대해 고민해보기 좋은 문제라 추가합니다~

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/103353395-1d585e80-4aec-11eb-8d68-371bc3435852.png)
해결했습니다~

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/103361835-a7102800-4afc-11eb-8be7-b3555199ac74.png)

해결했습니다.
