### ISSUE TITLE
[문제] 백준 / 골드4 / 1956 - 운동

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#278]
## 링크

https://www.acmicpc.net/problem/1956
## 비고

풀어보기 좋은 문제라 추천합니다! 유형은 맞춰보세요~

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/103794130-b60c5280-5087-11eb-8cd4-30e0049f091e.png)

겨우풀었네요 조건 하나를 못봐서 고생했어요

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/104150453-3252bd00-541d-11eb-9cd0-4696ba36ca93.png)

해결하였습니다.
