### ISSUE TITLE
[2021.01.18-2021.01.24] / 구현

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#303]
## 비고

[백준] [1713 후보 추천하기](https://www.acmicpc.net/problem/1713)
[백준] [13335 트럭](https://www.acmicpc.net/problem/13335)
[백준] [18405 경쟁적 전염](https://www.acmicpc.net/problem/18405)
[백준] [2116 주사위 쌓기](https://www.acmicpc.net/problem/2116)
[백준] [14499 주사위 굴리기](https://www.acmicpc.net/problem/14499)
[백준] [17140 이차원 배열과 연산](https://www.acmicpc.net/problem/17140)
[백준] [2174 로봇 시뮬레이션](https://www.acmicpc.net/problem/2174)
[백준] [1756 피자 굽기](https://www.acmicpc.net/problem/1756)
[백준] [10836 여왕벌](https://www.acmicpc.net/problem/10836)
[백준] [9207 페그 솔리테어](https://www.acmicpc.net/problem/9207)
[백준] [2002 추월](https://www.acmicpc.net/problem/2002)
[백준] [14719 빗물](https://www.acmicpc.net/problem/14719)
[백준] [12764 싸지방에 간 준하](https://www.acmicpc.net/problem/12764)
[백준] [1091 카드 섞기](https://www.acmicpc.net/problem/1091)
[백준] [3709 레이저빔은 어디로](https://www.acmicpc.net/problem/3709)
[백준] [20165 인내의 도미노 장인 호석](https://www.acmicpc.net/problem/20165)
[백준] [12739 돌림판 (Small)](https://www.acmicpc.net/problem/12739)
[백준] [17780 새로운 게임](https://www.acmicpc.net/problem/17780)
[백준] [3678 카탄의 개척자](https://www.acmicpc.net/problem/3678)
[백준] [18808 스티커 붙이기](https://www.acmicpc.net/problem/18808)

## 댓글에 푼 문제의 제출 현황을 올려주세요. 올리신 뒤 1/20 등으로 체크합니다.
* e.g. 해결했습니다. 1/20 || 해결했습니다! 2/20

* 주당 한 알고리즘 분류에서 20문제를 푸는 것을 목표로 합니다.
  * 한 문제가 어려우면 답을 보지 말고 최대한 쉬운 문제부터 풀어나가는 것으로 합니다.. (답을 보는 건 2시간 이상 고민했을 때, 최적화가 필요할 때, 아예 처음 보는 유형을 익히기 위할 때)
  * 8주를 헛되이지 않게 써 봅시다! 화이팅!

**Comment by OctopusSwellfish** [comment]
해결했습니다. 
진짜 저에게는 엄청 스트레스받는문제ㅔ였습니다
![image](https://user-images.githubusercontent.com/20165155/104919690-fd74d600-59d9-11eb-9f34-4bde682015bf.png)

1/20

**Comment by OctopusSwellfish** [comment]
해결했습니다.

시간이 느리네요..
![image](https://user-images.githubusercontent.com/20165155/104935173-3e76e580-59ee-11eb-8882-477db3ac4d29.png)

2/20

**Comment by OctopusSwellfish** [comment]
일주일만 더 늘려주실수있나요 ㅜㅜ 너무 바빠요

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/106637541-2d210200-65c6-11eb-8d01-c62eedf83978.png)
3/20 뒤늦게라도 열심히..ㅜ
