### ISSUE TITLE
[2021.01.19] 백준 / 실버 1 / 17615 - 볼 모으기

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#306]
## 링크

<https://www.acmicpc.net/problem/17615>

## 비고

오늘도 화이팅~ ^O^

D - 82

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/105020473-aed34480-5a8a-11eb-91d6-0f075a995b2c.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/105048708-329f2800-5aaf-11eb-9ab0-49c320927b12.png)
해결결했습니다
