### ISSUE TITLE
[2021.02.01] 백준 / 골드 4 / 14698 - 전생했더니 슬라임 연구자였던 건에 대하여 (Hard)

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#332]
## 링크

<https://www.acmicpc.net/problem/14698>

## 비고

오늘도 화이팅~ ^O^

D - 69

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/106625472-052ba180-65ba-11eb-9d6e-d22e6a183c40.png)

겨우풀었어어용 ㅜㅜ
