### ISSUE TITLE
[2021.02.18] 백준 / 골드 2 / 3109 - 빵집

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#361]
## 링크

<https://www.acmicpc.net/problem/3109>

## 비고

오늘도 화이팅~ ^O^

D - 52

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/108625045-000c9480-748c-11eb-8099-a9e292908561.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/108626057-9f805600-7491-11eb-803f-7043c8a36a61.png)
해결했습니당
