### ISSUE TITLE
[2021.02.20] 백준 / 실버 1 / 16948 - 데스 나이트

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#363]
## 링크

<https://www.acmicpc.net/problem/16948>

## 비고

오늘도 화이팅~ ^O^

D - 50

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/108591715-71294a80-73ad-11eb-8f58-54d24a805142.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/108593480-3d532280-73b7-11eb-9986-447baeb97efd.png)
해결했습니당!
