### ISSUE TITLE
[2021.03.28] 백준 / 골드 4 / 1197 - 최소 스패닝 트리

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#384]
## 링크

<https://www.acmicpc.net/problem/1197>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/112725168-29708280-8f5a-11eb-92f4-8eba60c45f3d.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/113344367-f10ee100-936b-11eb-80ef-a3508ad5872d.png)
해결했습니다~
