### ISSUE TITLE
[2021.03.31] 백준 / 골드 4 / 18223 - 민준이와 마산 그리고 건우

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#390]
## 링크

<https://www.acmicpc.net/problem/18223>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/113019099-3391bb80-91bc-11eb-95eb-a1c49cbf21ac.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/113038804-e4568580-91d1-11eb-9fb2-d8b440bf1dc7.png)
해결했습니다!
