### ISSUE TITLE
[2021.04.13] 백준 / 골드 5 / 2174 - 로봇 시뮬레이션

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#409]
## 링크

<https://www.acmicpc.net/problem/2174>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/114508682-9df03480-9c6f-11eb-86cd-95f49e48688f.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/114544513-b410eb80-9c95-11eb-8595-5b675d2bdc23.png)
해결했습니다. ok를 안 쓰니 틀려버리네요 ㅠ
