### ISSUE TITLE
[2021.04.14] SWEA / 5658 - 보물상자 비밀번호

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#412]
## 링크

<https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRUN9KfZ8DFAUo>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/114729619-1c85c880-9d7b-11eb-8caf-83faf8bedd73.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/115405377-2602ab00-a229-11eb-9f86-7e1b411ce939.png)
해결했습니다~!
