### ISSUE TITLE
[2021.04.15] SWEA / 5656 - 벽돌 깨기

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#414]
## 링크

<https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRQm6qfL0DFAUo>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/114888676-6d152880-9e44-11eb-9cc8-19a02bb30e8e.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/115549468-a84fa580-a2e3-11eb-856f-1c3b168cf7d9.png)
해결했습니다!
