### ISSUE TITLE
[2021.04.16] SWEA / 5653 - 줄기세포배양

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#417]
## 링크

<https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRJ8EKe48DFAUo>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/115141891-b601f280-a079-11eb-99f8-8853d3380059.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/115549971-43487f80-a2e4-11eb-93c9-e9c678243442.png)
해결했습니다!
