### ISSUE TITLE
[2021.04.17] SWEA / 5650 - 핀볼 게임

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#418]
## 링크

<https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRF8s6ezEDFAUo>

## 비고

오늘도 화이팅~ ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/115144527-15ff9580-a088-11eb-88a0-ff85f5d0b5f9.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/115246185-a01b2d00-a160-11eb-8b2f-9177f602a488.png)
해결했습니다.
