### ISSUE TITLE
[2021.04.21] SWEA / 2383 - 점심 식사시간

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#427]
## 링크

<https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5-BEE6AK0DFAVl>

## 비고

오늘도 화이팅~ ^O^

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/115587273-756bd880-a308-11eb-9b51-2cd5209e092a.png)
해결했습니다..진짜 어려운문제

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/115719887-7c9def80-a3b7-11eb-9704-d8037fdb7a47.png)

해결하였습니다.
