### ISSUE TITLE
[문제] 백준 / 골드5 / 18513 - 샘터

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#62]
## 링크

https://www.acmicpc.net/problem/18513
## 비고

이 문제도 풀어보면 좋을 것 같아서 추가합니다.

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/95222768-ce27c800-0833-11eb-9c18-81bf2b9c00aa.png)

2020/10/06 
해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/95708510-6fc97200-0c97-11eb-8063-643ea06370ec.png)

2020/10/12
늦었지만 저도 해결했습니다..!
