### ISSUE TITLE
[2020.10.06] 백준 / 골드 2 / 16946 - 벽 부수고 이동하기 4

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#63]
## 링크

<https://www.acmicpc.net/problem/16946>

## 비고

벽을 부수고 이동해봅시다! 오늘도 화이팅 ^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/95221923-e9de9e80-0832-11eb-96cf-ceb006b13a1c.png)

2020/10/06
해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/97105235-ae7e1400-16fc-11eb-8cca-50c8a5641f9b.png)
겨우 풀어냈네요 ;; 자꾸 시간초과나서 어려웠습니다. 좋은 문제였습니다. 감사합니다.
