### ISSUE TITLE
[2020.10.08] 백준 / 골드4 / 16235 - 나무 제테크

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#69]
## 링크

https://www.acmicpc.net/problem/16235

## 비고

삼성전자 기출입니다!

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/95649220-6b764b00-0b17-11eb-853d-a4d895fe6478.png)

2020/10/08
해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/96002449-14081000-0e74-11eb-857a-228903e414c4.png)

전 왜이렇게 느린거죠 ㅋㅋㅋ 해결했습니다.
