### ISSUE TITLE
[2020.10.09] 백준 / 골드2 / 17143 - 낚시왕

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#73]
## 링크

https://www.acmicpc.net/problem/17143
## 비고

비슷한 문제 풀어보세용

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/95749122-10d71d80-0cd6-11eb-9ce7-32258511483f.png)

2020/10/09
해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/96163588-08d8e100-0f55-11eb-8e10-eb6b6ce53aed.png)
2020/10/16
해결했습니다.
