### ISSUE TITLE
[2020.10.10] 백준 / 골드3 / 19237 - 어른 상어

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#75]
## 링크

<https://www.acmicpc.net/problem/19237>

## 비고

청소년 상어에 이은 마지막 어른 상어를 풀어봅시다~^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/95750272-d8384380-0cd7-11eb-9f04-6cbf0e0d125e.png)

2020/10/10
해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/96088634-ad7d0380-0f00-11eb-81ff-0ed28b38d84d.png)

해결했습니다~!
