### ISSUE TITLE
[문제] 백준 / 실버5 / 10158 - 개미

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#77]
## 링크

https://www.acmicpc.net/problem/10158
## 비고

좌표에 대한 값을 공부해보기 좋은 아주 좋은 문제였다고 생각해서 올립니다.

**Comment by OctopusSwellfish** [comment]
제게 수학적인 능력이 없는지 이 문제조차 어렵게 느껴졌습니다 ㅜㅜ

어쨌든 해결했습니다. 실버5치고 정말 어려웠던것 같네요..저에겐.

![image](https://user-images.githubusercontent.com/20165155/95717310-b6bf6380-0ca7-11eb-9b5d-d77e88391903.png)

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96263907-8d336e80-0ffe-11eb-95dd-2a95ba9ddce7.png)

해결하였습니다. ASK...
