### ISSUE TITLE
[2020.10.12] 백준 / 골드 2 / 17837 - 새로운 게임 2

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#80]
## 링크

<https://www.acmicpc.net/problem/17837>

## 비고

새로운 게임을 시작해봅시다. 오늘도 화이팅!^O^

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/95887647-1195af80-0dbb-11eb-91e6-e479cb7da27f.png)

풀었습니다!

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96070962-2d44a700-0edc-11eb-98e1-6b58e2f5fcf5.png) 

해결하였습니다.
