### ISSUE TITLE
[2020.10.13] 백준 / 골드 3 / 17822 - 원판 돌리기

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#85]
## 링크

<https://www.acmicpc.net/problem/17822>

## 비고

원판을 돌려봅시다 오늘도 화이팅!^O^

**Comment by OctopusSwellfish** [comment]
후..

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/95867867-95906d00-0da4-11eb-80a0-8f81e76b1c13.png)

해결했습니다. 생각보다 까다로운 문제였군요...

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/95877159-c70e3600-0dae-11eb-8a04-7d856d0476ec.png)

2020/10/13
해결하였습니다.
