### ISSUE TITLE
[2020.10.14] 백준 / 골드 4 / 17779 - 게리맨더링 2

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#88]
## 링크

<https://www.acmicpc.net/problem/17779>

## 비고

제목이 뭔뜻인지는 모르겠지만, 오늘도 화이팅~^O^

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/96018612-7538df00-0e86-11eb-989a-2f9d125ae997.png)
와 진짜 엄청빡세네요.... 구 나누는거까진 어떻게 했는데 구역을 칠하는 게 엄청 오래걸렸습니다 ㅜㅠ

> 게리맨더링은 특정 후보자의 당선을 유리하게 하거나 특정 정당이 더 많은 의석을 확보하도록 선거구를 지리적인 구역과 다르게 기형적인 모양으로 분할하는 것을 말한다. 이를 막기 위해서 대한민국에서는 선거구를 법률로 정하게 하고 있으며, 기본적으로 행정구역의 경계에 따르도록 하고 있다.

왈왈왈...

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96154543-e5f4ff80-0f49-11eb-9fb6-bc74259da07c.png)

해결하였....나 안했나 모르겠습니다 너무어렵네요 ㅠ.ㅠ
