### ISSUE TITLE
[문제] 백준 / 골드5 / 14503 - 로봇 청소기

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#89]
## 링크

https://www.acmicpc.net/problem/14503
## 비고

좋은 구현 문제인거 같아서 공유합니다!

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96203334-9be93980-0f9c-11eb-8a3f-1f41f786c9c8.png)

해결하였습니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/97846911-11d9f880-1d32-11eb-8706-c7b0cc12c9b2.png)
해결했습니다!
