### ISSUE TITLE
[2020.10.15] 백준 / 플레 5 / 19235 - 모노미노도미노

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#90]
## 링크

<https://www.acmicpc.net/problem/19235>

## 비고

대망의 모노미노도미노입니다. 화이팅~^O^

**Comment by OctopusSwellfish** [comment]
후..이거 정녕 해야하는겁니까 ㅜ 문제 진짜 길던뎅..

**Comment by HyeonJinGitHub** [comment]
> 후..이거 정녕 해야하는겁니까 ㅜ 문제 진짜 길던뎅..

해야합니다....ㅠ
