### ISSUE TITLE
[문제] 백준 / 골드5 / 17144 - 미세먼지 안녕!

### ISSUE THREAD

**Issue by OctopusSwellfish** [HyeonJinGitHub/LearningRepository#93]
## 링크

https://www.acmicpc.net/problem/17144
## 비고

정말 배열 인덱스 공부하기 좋은 문제라 추가합니다.

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/96142947-96a8d200-0f3d-11eb-94a2-9d98e21d502e.png)

배열열 돌리기 개 헬...진짜너무어려웠네요 ㅜㅜ

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96222047-8983f580-0fc6-11eb-9f07-2236e6012782.png)

해결하였습니다..ㅠ
