### ISSUE TITLE
[2020.10.16] 백준 / 골드 5 / 15686 - 치킨 배달

### ISSUE THREAD

**Issue by HyeonJinGitHub** [HyeonJinGitHub/LearningRepository#96]
## 링크

<https://www.acmicpc.net/problem/15686>

## 비고

치킨치킨치킨~ 오늘도 화이팅!^O^

**Comment by HyeonJinGitHub** [comment]
![image](https://user-images.githubusercontent.com/46698840/96226556-c56e8900-0fcd-11eb-88bd-8334eb93a562.png)

해결하였습니다. BFS로 풀었더니 조금 느린것 같습니다..

**Comment by OctopusSwellfish** [comment]
![image](https://user-images.githubusercontent.com/20165155/97848991-3d121700-1d35-11eb-936a-407f132703e8.png)

해결했습니다 !
